### ISSUE TITLE
tautulli ip

### ISSUE THREAD

**Issue by chiggerz** [CyaOnDaNet/plex_discord_role_management#12]
hey, anyone know what I need to put as the IP address if I'm using a domain?  

Im setting up docker fine and bot is online, but it just cannot connect to Tautulli and error is about the IP address. 

I think I have tried everything, but if anyone can help?

TIA

**Comment by CyaOnDaNet** [comment]
I haven't had any issues using a URL instead of an IP in my testing. To do that, leave the port field blank and specify the entire URL in the IP field. Don't forget to specify http:// or https://. For example, if you normally access the home page of tautulli at https://tautulli.example.com/home, you would specify https://tautulli.example.com/ in the IP field. It works if you have a different webroot too, just take whatever the URL is you use to access tautulli and drop the home off the end.

If you continue to run into issues, let me know. For now I will close this issue.

**Comment by chiggerz** [comment]
Thanks for the reply, but I must have something else set wrong as im still getting same issue.  This is what im getting in the container log.  Any ideas?  Im still learning with all this, so not sure if the ports are set correctly?

The bot is now online!

Webhook Service: Tautulli Listening on docker port:3000 and host port:3000

Tautulli Webhhok Startup Connection refused, retrying in 30 seconds...

FetchError: request to http://your_tautulli_ip_address/:YOUR_TAUTULLI_PORT/api/v2?apikey=YOUR_TAUTULLI_API_KEY&cmd=get_activity&out_type=json failed, reason: getaddrinfo ENOTFOUND your_tautulli_ip_address

    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1461:11)

    at ClientRequest.emit (events.js:314:20)

    at Socket.socketErrorListener (_http_client.js:428:9)

    at Socket.emit (events.js:314:20)

    at emitErrorNT (internal/streams/destroy.js:92:8)

    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)

    at processTicksAndRejections (internal/process/task_queues.js:84:21) {

  type: 'system',

  errno: 'ENOTFOUND',

  code: 'ENOTFOUND'

}

~Tautulli Webhhok Startup~ Connection refused [Attempt #2], retrying in 30 seconds...
